export enum COMMENTS_ACTION_TYPES {
  CREATE_COMMENT_START = 'comments/CREATE_COMMENT_START',
  CREATE_COMMENT_SUCCESS = 'comments/CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE = 'comments/CREATE_COMMENT_FAILURE',
  DELETE_COMMENT_START = 'comments/DELETE_COMMENT_START',
  DELETE_COMMENT_SUCCESS = 'comments/DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE = 'comments/DELETE_COMMENT_FAILURE',
  FETCH_COMMENTS_START = 'comments/FETCH_COMMENTS_START',
  FETCH_COMMENTS_SUCCESS = 'comments/FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_FAILURE = 'comments/FETCH_COMMENTS_FAILURE',
}
