export enum TODOS_ACTION_TYPES {
  GET_TODOS_START = 'todos/GET_TODOS_START',
  DELETE_TODO_START = 'todos/DELETE_TODO_START',
  EDIT_TODO_START = 'todos/EDIT_TODO_START',
  CREATE_TODO_START = 'todos/CREATE_TODO_START',
  FETCH_TODOS_SUCCESS = 'todos/FETCH_TODOS_SUCCESS',
  DELETE_TODO_SUCCESS = 'todos/DELETE_TODO_SUCCESS',
  EDIT_TODO_SUCCESS = 'todos/EDIT_TODO_SUCCESS',
  CREATE_TODO_SUCCESS = 'todos/CREATE_TODO_SUCCESS',
  FETCH_TODOS_FAILURE = 'todos/FETCH_TODOS_FAILURE',
  TODO_STATUS_CHECK = 'todos/TODO_STATUS_CHECK',
}
